##version: "3.7"
x-logging:
  &logging
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "3"

services:
    mongodb:
        image: mongodb/mongodb-community-server:latest
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: MongoDB2024!
        ports:
            - "27017:27017"
        volumes:
            - /data:/data/db
        networks:
            - oliveira-trust
        <<: *logging

    redis:
        image: redis:3.2.5-alpine
        container_name: redis
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - oliveira-trust
        <<: *logging

    api:
        build:
            args:
                user: www-data
                uid: 1000
            context: ./
            dockerfile: ./Dockerfile
        image: api
        container_name: api
        ports:
            - "8000:8000"
        restart: unless-stopped
        working_dir: /var/www/html/oltrust
        environment:
            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/html/oltrust
        volumes:
            - /home/gustavo/projects/desafios/oliveiraTrust:/var/www/html/oltrust
        depends_on:
            - redis
            - mongodb
        networks:
            - oliveira-trust
        <<: *logging


networks:
    oliveira-trust:
        driver: bridge

